<?php
if (!isset($TEMPLATE)) {
  $TITLE = "Technical Terms used on Event Pages";
  include_once 'template.inc.php';
}
?>

<a id="magnitude"></a>
<h2>Magnitude</h2>

<p>
  Earthquake magnitude is a measure of the size of an earthquake at its source.
  It is a logarithmic measure.  At the same distance from the earthquake, the
  amplitude of the seismic waves from which the magnitude is determined are
  approximately 10 times as large during a magnitude 5 earthquake as during a
  magnitude 4 earthquake. The total amount of energy released by the earthquake
  usually goes up by a larger factor: for many commonly used magnitude types,
  the total energy of an average earthquake goes up by a factor of
  approximately 32 for each unit increase in magnitude. There are various ways
  that magnitude may be calculated from seismograms. Different methods are
  effective for different sizes of earthquakes and different distances between
  the earthquake source and the recording station. The various magnitude types
  are generally defined so as to yield magnitude values that agree to within a
  few-tenths of a magnitude-unit for earthquakes in a middle range of
  recorded-earthquake sizes, but the various magnitude-types may have values
  that differ by more than a magnitude-unit for very large and very small
  earthquakes as well as for some specific classes of seismic source. This is
  because earthquakes are commonly complex events that release energy over a
  wide range of frequencies and at varying amounts as the faulting or rupture
  process occurs.  The various types of magnitude measure different aspects of
  the seismic radiation (e.g., low-frequency energy vs. high-frequency energy).
  The relationship among values of different magnitude types that are assigned
  to a particular seismic event may enable the seismologist to better
  understand the processes at the focus of the seismic event.  The various
  magnitude-types are not all available at the same time for a particular
  earthquake.  Preliminary magnitudes based on incomplete but rapidly-available
  data are sometimes estimated and reported. For example, the Tsunami Warning
  Centers will calculate a preliminary magnitude and location for an event as
  soon as sufficient data are available to make an estimate. In this case, time
  is of the essence in order to broadcast a warning if tsunami waves are likely
  to be generated by the event. Such preliminary magnitudes are superseded by
  improved estimates of magnitude as more data become available. For large
  earthquakes of the present era, the magnitude that is ultimately selected as
  the preferred magnitude for reporting to the public is commonly a moment
  magnitude that is based on the scalar seismic-moment of an earthquake
  determined by calculation of the seismic moment-tensor that best accounts for
  the character of the seismic waves generated by the earthquake.  The scalar
  seismic-moment, a parameter of the seismic moment-tensor, can also be
  estimated via the multiplicative product rigidity of faulted rock x area of
  fault rupture x average fault displacement during the earthquake.
</p>

<h2>
  Magnitudes commonly used by seismic networks include:
</h2>

<table class="tabular">
  <thead>
    <tr>
      <th>Magnitude type</th>
      <th>Magnitude Range</th>
      <th>Distance Range</th>
      <th>Comments</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Duration (Md or md)</td>
      <td>&lt; 4</td>
      <td>0 - 400 km</td>
      <td>
        Based on the duration of shaking as measured by the time decay of the
        amplitude of the seismogram.  Often used to compute magnitude from
        seismograms with &ldquo;clipped&rdquo; waveforms due to limited dynamic
        recording range of analog instrumentation, which makes it impossible to
        measure peak amplitudes.
      </td>
    </tr>
    <tr>
      <td>Local (ML Ml, or ml)</td>
      <td>2 - 7.5</td>
      <td>0 - 600 km</td>
      <td>
        The original magnitude relationship defined by Richter and Gutenberg for
        local earthquakes in 1935. It is based on the maximum amplitude of a
        seismogram recorded on a Wood-Anderson torsion seismograph. Although
        these instruments are no longer widely in use, ML values are calculated
        using modern instrumentation with appropriate adjustments.
      </td>
    </tr>
    <tr>
      <td>Short-period surface wave (mb_Lg, mb_lg, or MLg)</td>
      <td>3.5 - 7</td>
      <td>150 – 1100 km</td>
      <td>
        A magnitude for regional earthquakes based on the amplitude of the Lg
        surface waves as recorded on short-period instruments.
      </td>
    </tr>
    <tr>
      <td>Short-period body wave (mb)</td>
      <td>4 - 7</td>
      <td>15 - 100 degrees </td>
      <td>
        Based on the amplitude of P body-waves as recorded on short-period
        instruments that are most sensitive to waves with a period of about
        1 s.
      </td>
    </tr>
    <tr>
      <td>Twenty-second surface wave (Ms or Ms_20)</td>
      <td>5 - 8.5</td>
      <td>20 - 160 degrees</td>
      <td>
        A magnitude for distant earthquakes based on the amplitude of Rayleigh
        surface waves measured at a period near 20 sec.
      </td>
    </tr>
    <tr>
      <td>Moment (generic notation Mw or mw.  Specific types denoted Mwb or
        mwb, Mwc or mwc, Mwr or mwr, and Mww or mww)</td>
      <td>&gt; 3.5</td>
      <td>all</td>
      <td>
        Based on the scalar seismic-moment of the earthquake, as determined by
        a moment-tensor inversion. Mwb – Mw based on moment tensor inversion of
        long-period (~10 - 100 s) body-waves (P- and SH).  Mwc -- Moment
        magnitude derived from a centroid moment tensor inversion of
        intermediate- and long-period body- and surface-waves.  Mwr -- Moment
        magnitude derived from a moment tensor inversion of complete waveforms
        at regional distances (less than ~13 degrees). Sometimes called RMT.
        Mww -- Moment magnitude derived from a centroid moment tensor inversion
        of the W-phase.
      </td>
    </tr>
    <tr>
      <td>Moment (Mi or Mwp)</td>
      <td>5 - 8</td>
      <td>all</td>
      <td>
        Based on an estimate of moment calculated from the integral of the
        displacement of the P wave recorded on broadband instruments.
      </td>
    </tr>
    <tr>
      <td>Energy (Me)</td>
      <td>&gt; 3.5</td>
      <td>all</td>
      <td>
        Based on the seismic energy radiated by the earthquake as estimated by
        integration of  digital waveforms
      </td>
    </tr>
  </tbody>
</table>

<a id="eventTime"></a>
<h2>Event Time</h2>

<p>
  We indicate the date and time when the earthquake initiates rupture, which is
  known as the "origin" time. Note that large earthquakes can continue rupturing
  for many 10's of seconds. We provide time in UTC (Coordinated Universal Time).
  Seismologists use UTC to avoid confusion caused by local time zones and
  daylight savings time. On the individual event pages, times are also provided
  for the time at the epicenter, and your local time based on the time your
  computer is set.
</p>

<a id="location"></a>
<h2>Location</h2>

<p>
  An earthquake begins to rupture at a hypocenter which is defined by a position
  on the surface of the earth (epicenter) and a depth below this point (focal
  depth). We provide the coordinates of the epicenter in units of latitude and
  longitude. The latitude is the number of degrees north (N) or south (S) of the
  equator and varies from 0 at the equator to 90 at the poles. The longitude is
  the number of degrees east (E) or west (W) of the prime meridian which runs
  through Greenwich, England. The longitude varies from 0 at Greenwich to 180
  and the E or W shows the direction from Greenwich. Coordinates are given in
  the
  <a href="http://earth-info.nga.mil/GandG/publications/tr8350.2/tr8350_2.html">
  WGS84</a> reference frame. The position uncertainty of the hypocenter location
  varies from about 100 m horizontally and 300 meters vertically for the best
  located events, those in the middle of densely spaced seismograph networks, to
  10s of kilometers for global events in many parts of the world.
</p>

<a id="depth"></a>
<h2>Depth</h2>

<p>
  The depth where the earthquake begins to rupture. This depth may be relative
  to mean sea-level or the average elevation of the seismic stations which
  provided arrival-time data for the earthquake location. The choice of
  reference depth is dependent on the method used to locate the earthquake.
  Sometimes when depth is poorly constrained by available seismic data, the
  location program will set the depth at a fixed value. For example, 33 km is
  often used as a default depth for earthquakes determined to be shallow, but
  whose depth is not satisfactorily determined by the data, whereas default
  depths of 5 or 10 km are often used in mid-continental areas and on mid-ocean
  ridges since earthquakes in these areas are usually shallower than 33 km.
</p>

<a id="nearbyCities"></a>
<h2>Nearby Cities</h2>

<p>
  We provide distances and directions from nearby geographical reference points
  to the earthquake. The reference points are towns, cities, and major
  geographic features derived from US Census data, such as from
  <a href="https://www.census.gov/geo/www/gazetteer/places2k.html">
  http://www.census.gov/geo/www/gazetteer/places2k.html</a>. International
  places were gathered from a specially created USGS catalog. Selected places
  were based on minimum population values that were specified for each
  particular region.
</p>

<p>
  We realize that these distances are uncertain both because of the errors
  inherent in locating earthquake (typically one or more kilometers) and because
  of the impossibility of describing the location of a city by a single
  longitude-latitude entry in a table. For places in the US, rather than
  rounding off distances to, say, the nearest 10 kilometers, we chose to trust
  the user's common sense in interpreting the accuracy of these distances. For
  places outside the US, distances are rounded depending on the
  <a href="#locationUncertainty">location uncertainty</a>. If the computed
  location is close to an operating quarry which is known to use explosives in
  its operations, we indicate that the event may be a quarry explosion. We try
  to always provide at least one widely recognized reference point in the list
  on the event page, even if the earthquake occurs in a remote location.
</p>

<a id="magnitudeUncertainty"></a>
<h2>Magnitude Uncertainty</h2>

<p>
  The estimated standard error of the magnitude. The uncertainty corresponds to
  the specific magnitude type being reported and does not take into account
  magnitude variations and biases between different magnitude scales. We report
  an "unknown" value if the contributing seismic network does not supply
  uncertainty estimates.
</p>

<a id="locationUncertainty"></a>
<h2>Location Uncertainty</h2>

<p>
  The horizontal location error, in km, defined as the length of the largest
  projection of the three principal errors on a horizontal plane. The principal
  errors are the major axes of the error ellipsoid, and are mutually
  perpendicular. The horizontal and vertical uncertainties in an event's
  location varies from about 100 m horizontally and 300 meters vertically for
  the best located events, those in the middle of densely spaced seismograph
  networks, to 10s of kilometers for global events in many parts of the world.
  We report an "unknown" value if the contributing seismic network does not
  supply uncertainty estimates.
</p>

<a id="depthUncertainty"></a>
<h2>Depth Uncertainty</h2>

<p>
  The depth error, in km, defined as the largest projection of the three
  principal errors on a vertical line.
</p>

<a id="azmithulGap"></a>
<h2>Azimuthal Gap</h2>

<p>
  The largest azimuthal gap between azimuthally adjacent stations (in degrees).
  In general, the smaller this number, the more reliable is the calculated
  horizontal position of the earthquake. Earthquake locations in which the
  azimuthal gap exceeds 180 degrees typically have large location and depth
  uncertainties.
</p>

<a id="nst"></a>
<h2>Number of Stations Used</h2>

<p>
  Number of seismic stations which reported P- and S-arrival times for this
  earthquake. This number may be larger than the Number of Phases Used if
  arrival times are rejected because the distance to a seismic station exceeds
  the maximum allowable distance or because the arrival-time observation is
  inconsistent with the solution.
</p>

<a id="nph"></a>
<h2>Number of Phases Used</h2>

<p>
  Number of P and S arrival-time observations used to compute the hypocenter
  location. Increased numbers of arrival-time observations generally result in
  improved earthquake locations.
</p>

<a id="dmin"></a>
<h2>Minimum Distance</h2>

<p>
  Horizontal distance from the epicenter to the nearest station (in km). In
  general, the smaller this number, the more reliable is the calculated depth of
  the earthquake.
</p>

<a id="rmss"></a>
<h2>Travel Time Residual</h2>

<p>
  The root-mean-square (RMS) travel time residual, in sec, using all weights.
  This parameter provides a measure of the fit of the observed arrival times to
  the predicted arrival times for this location. Smaller numbers reflect a
  better fit of the data. The value is dependent on the accuracy of the velocity
  model used to compute the earthquake location, the quality weights assigned to
  the arrival time data, and the procedure used to locate the earthquake.
</p>

<a id="reviewStatus"></a>
<h2>Review Status</h2>

<p>
  Review status is either automatic or reviewed.  Automatic events are directly
  posted by automatic processing systems and have not been verified or
  altered by a human. Reviewed events have been looked at by a human. The level
  of review can range from a quick validity check to a careful reanalysis of
  the event.
</p>

<a id="eventID"></a>
<h2>Event ID</h2>

<p>
  A combination of a 2-letter
  <a href="http://www.iris.edu/stations/networks.txt">Seismic Network Code</a>
  and a number assigned by the contributing seismic network.
</p>

<a id="momentTensors"></a>
<h2>Moment Tensors</h2>

<p>
  A mathematical representation of the movement on a fault during an earthquake.
  The tensor depends on the source strength and fault orientation. See also
  <a href="/learn/topics/beachball.php">Focal Mechanisms</a>
</p>
