'use strict';


var BasicPinView = require('core/BasicPinView'),
    DYFIFormModule = require('dyfi/DYFIFormModule'),
    Formatter = require('core/Formatter'),
    Util = require('util/Util');

var _DEFAULTS = {
  module: DYFIFormModule
};


var DYFIFormPinView = function (options) {
  var _this,
      _initialize,

      _formatter;


  options = Util.extend({}, _DEFAULTS, options);
  _this = BasicPinView(options);

  _initialize = function (options) {
    _formatter = options.formatter || Formatter();
  };


  /**
   * Frees resources associated with this view.
   *
   */
  _this.destroy = Util.compose(function () {
    if (_this === null) {
      return;
    }

    _formatter = null;

    _initialize = null;
    _this = null;
  }, _this.destroy);

  /**
   * Render the histograms as DYFIFormPinView content
   *
   */
  _this.renderPinContent = function () {
    var markup,
        pad,
        responses,
        stillZero,
        value;

    markup = [];
    pad = '000000';

    responses = _this.model.getProperty('num-responses') ||
        _this.model.getProperty('numResp') || '0';
    // pad with zeros
    responses = _formatter.leftPad(responses.toString(), 6, '0');
    stillZero = true;

    for (var i = 0, len = responses.length; i < len; i += 1) {
      value = responses.charAt(i);

      if (value === '0' && stillZero) {
        markup.push('<div class="responses-digit empty-digit">0</div>');
      } else {
        stillZero = false;
        markup.push('<div class="responses-digit">', value, '</div>');
      }
    }

    _this.content.innerHTML =
      '<div class="dyfi-responses-badge" title="Number of DYFI Responses">' +
        markup.join('') +
      '</div>' +
      '<div class="dyfi-responses-abbr">' +
        '<abbr title="Number of DYFI Responses">Responses</abbr>' +
      '</div>' +
      '<small class="disclaimer">' +
        'Contribute to citizen science. Please <a href="#tellus">tell us</a> ' +
        'about your experience.' +
      '</small>';
  };

  /**
   * Use custom attribution as this content is generated by user-submitted
   * felt reports from the "Tell Us!" link.
   *
   */
  _this.renderPinFooter = function () {
    _this.footer.innerHTML = 'Citizen Scientist Contributions';
  };


  _initialize(options);
  options = null;
  return _this;
};

module.exports = DYFIFormPinView;
